-- MySQL Script generated by MySQL Workbench
-- Wed Aug 22 11:44:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
CREATE DATABASE test_ewidencja DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE test_ewidencja;
-- -----------------------------------------------------
--  
-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `department` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `Department` VARCHAR(50) NOT NULL,
  `Director` INT NULL,
  `Type` VARCHAR(11) NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `Director_UNIQUE` ON `department` (`Director` ASC);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users`;

CREATE TABLE IF NOT EXISTS users (
	idUser INT NOT NULL AUTO_INCREMENT,
	Login VARCHAR(25) NOT NULL,
	Password VARCHAR(130) NOT NULL,
	DatePas DATETIME NULL,
	idPerson INT NULL,
	`Admin` TINYINT(1) NOT NULL,
	`IT` TINYINT(1) NOT NULL,
	`User` TINYINT(1) NOT NULL,
	Password1 VARCHAR(25) NULL,
	DatePas1 DATE NULL,
	Password2 VARCHAR(25) NULL,
	DatePas2 DATE NULL,
	Password3 VARCHAR(25) NULL,
	DatePas3 DATE NULL,
	PRIMARY KEY (idUser)
)ENGINE = InnoDB;
SHOW WARNINGS;

CREATE UNIQUE INDEX Users_UNIQUE ON users (`Login` ASC);
SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `person` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(30) NOT NULL,
  `idDepartment` INT NULL,
  `idCity` INT NULL,
  `NumberPhone` VARCHAR(55) NULL,
  `DateEmployment` DATE NULL,
  `Work` TINYINT(1) NOT NULL,
  `DateRelease` DATE NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `personCompany`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personCompany` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `personCompany` (
  `idPerson` INT NOT NULL,
  `idCompany` INT NOT NULL
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `company` 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `NameCompany` VARCHAR(35) NOT NULL,
  `NIP` VARCHAR(10) NULL,
  `idCity` INT NULL,
  `NumberPhone` VARCHAR(16) NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `city` 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `city` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `city` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `NameCity` VARCHAR(35) NOT NULL,
  `PostCode` VARCHAR(6) NULL,
  `Street` VARCHAR(30) NULL,
  `NoHouse` VARCHAR(5) NULL,
  `NoFlat` VARCHAR(8) NULL,
  PRIMARY KEY (`idCity`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `NameCity_UNIQUE` ON `city` (`NameCity` ASC);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mailbox`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mailbox` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `mailbox` (
  `idMailbox` INT NOT NULL AUTO_INCREMENT,
  `AdresEmail` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(30) NULL,
  `PersonalType` TINYINT(1) NOT NULL,
  `AliasType` TINYINT(1) NOT NULL,
  `GroupeType` TINYINT(1) NOT NULL,
  `DateCreation` DATE NULL,
  `Active` TINYINT(1) NOT NULL,
  `DateBlocked` DATE NULL,
  `DateDeleted` DATE NULL,
  PRIMARY KEY (`idMailbox`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `AdresEmail_UNIQUE` ON `mailbox` (`AdresEmail` ASC);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `office` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `office` (
  `idOffice` INT NOT NULL AUTO_INCREMENT,
  `Office` VARCHAR(15) NULL,
  `Version` VARCHAR(20) NOT NULL,
  `KeyOffline` VARCHAR(29) NOT NULL,
  `DateAdd` DATE NULL,
  `idEmailAdd` INT NULL,
  `KeyOnline` VARCHAR(29) NULL,
  `idInvoice` INT NULL,
  PRIMARY KEY (`idOffice`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `KeyOffline_UNIQUE` ON `office` (`KeyOffline` ASC);
SHOW WARNINGS;

CREATE UNIQUE INDEX `KeyOnline_UNIQUE` ON `office` (`KeyOnline` ASC);
SHOW WARNINGS;

CREATE INDEX `FK_invoice_idx` ON `office` (`idInvoice` ASC);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comments`;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `comments`(
	`idComments` INT NOT NULL AUTO_INCREMENT,
	`idPerson` INT NOT NULL,
	`idComputers` INT NOT NULL,
	`idDevice` INT NOT NULL,
	`Comment` VARCHAR(255) NOT NULL,
	`DateAdd` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (`idComments`))
ENGINE = InnoDB;
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `computers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `computers` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `computers` (
  `idComputers` INT NOT NULL AUTO_INCREMENT,
  `Producer` VARCHAR(20) NULL,
  `Model` VARCHAR(35) NULL,
  `ComputerName` VARCHAR(20) NOT NULL,
  `SerialNumber` VARCHAR(20) NULL,
  `OperatingSystem` VARCHAR(25) NOT NULL,
  `idPerson` INT NULL,
  `idStatusComputer` INT NOT NULL,
  `Encrypted` TINYINT(1) NULL,
  `IdentifierBitLocker` VARCHAR(40) NULL,
  `RecoveryKeyNitLocker` VARCHAR(60) NULL,
  `PasswordEncrypted` VARCHAR(25) NULL,
  `DateEncrypted` DATE NULL,
  `MacEthernet` VARCHAR(17) NULL,
  `MacWiFi` VARCHAR(17) NULL,
  `idOffice` INT NULL,
  `idInvoice` INT NULL,
  PRIMARY KEY (`idComputers`),
  UNIQUE (`idOffice`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `ComputerName_UNIQUE` ON `computers` (`ComputerName` ASC);
SHOW WARNINGS;

CREATE UNIQUE INDEX `SerialNumber_UNIQUE` ON `computers` (`SerialNumber` ASC);
SHOW WARNINGS;

CREATE UNIQUE INDEX `IdentifierBitLocker_UNIQUE` ON `computers` (`IdentifierBitLocker` ASC);
SHOW WARNINGS;

CREATE UNIQUE INDEX `RecoveryKeyNitLocker_UNIQUE` ON `computers` (`RecoveryKeyNitLocker` ASC);
SHOW WARNINGS;

CREATE UNIQUE INDEX `MacEthernet_UNIQUE` ON `computers` (`MacEthernet` ASC);
SHOW WARNINGS;

CREATE UNIQUE INDEX `MacWiFi_UNIQUE` ON `computers` (`MacWiFi` ASC);
SHOW WARNINGS;

CREATE INDEX `FK_invoice_idx` ON `computers` (`idInvoice` ASC);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `company` 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statusComputer` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `statusComputer` (
  `idStatusComputer` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idstatusComputer`))
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `email` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `email` (
  `idMailBox` INT NOT NULL,
  `idPersonal` INT NOT NULL
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `NumberInvoice` VARCHAR(30) NOT NULL,
  `Date` DATE NOT NULL,
  `GrosPrice` DOUBLE NOT NULL,
  `Shop` VARCHAR(45) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`idInvoice`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `NumberInvoice_UNIQUE` ON `invoice` (`NumberInvoice` ASC);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permissions` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `permissions` (
  `idPermissions` INT NOT NULL AUTO_INCREMENT,
  `idPerson` INT NOT NULL,
  `ActiveAccount` TINYINT(1) NOT NULL DEFAULT 1,
  `GroupUsers` TINYINT(1) NOT NULL DEFAULT 0,
  `GroupAdmins` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPermissions`),
  UNIQUE (`idPerson`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nameShares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nameShares` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `nameShares` (
  `idNameShares` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `AddressShares` VARCHAR(40),
  PRIMARY KEY (`idNameShares`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `networkShares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `networkShares` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `networkShares` (
  `idNetworkShares` INT NOT NULL AUTO_INCREMENT,
  `idName` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `AllPermission` TINYINT(1) NOT NULL DEFAULT 0,
  `Write` TINYINT(1) NOT NULL,
  `Read` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idNetworkShares`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `device` (
  `idDevice` INT NOT NULL AUTO_INCREMENT,
  `NameDevice` VARCHAR(40) NOT NULL,
  `Producer` VARCHAR(40) NOT NULL,
  `Model` VARCHAR(35) NULL,
  `SerialNumber` VARCHAR(25) NOT NULL,
  `Warranty` VARCHAR(15) NULL,
  `idPerson` INT NULL,
  `idInvoice` INT NULL,
  `idStatus` INT NOT NULL,
  `ReleaseDate` DATE NULL,
  PRIMARY KEY (`idDevice`))
ENGINE = InnoDB;

SHOW WARNINGS;

CREATE UNIQUE INDEX `SerialNumber_UNIQUE` ON `device` (`SerialNumber` ASC);
SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE email ADD FOREIGN KEY (`idPersonal`) REFERENCES person (`idPerson`);

ALTER TABLE email ADD FOREIGN KEY (`idMailBox`) REFERENCES mailbox (`idMailBox`);

ALTER TABLE permissions ADD FOREIGN KEY (`idPerson`) REFERENCES person (`idPerson`);

ALTER TABLE networkShares ADD FOREIGN KEY (`idPerson`) REFERENCES person (`idPerson`);

ALTER TABLE networkShares ADD FOREIGN KEY (`idName`) REFERENCES nameShares (`idNameShares`);

ALTER TABLE department ADD FOREIGN KEY (`Director`) REFERENCES person (`idPerson`);

ALTER TABLE person ADD FOREIGN KEY (`idDepartment`) REFERENCES department (`idDepartment`);

ALTER TABLE person ADD FOREIGN KEY (`idCity`) REFERENCES city (`idCity`);

ALTER TABLE personCompany ADD FOREIGN KEY (`idPerson`) REFERENCES person (`idPerson`);

ALTER TABLE personCompany ADD FOREIGN KEY (`idCompany`) REFERENCES company (`idCompany`);

ALTER TABLE company ADD FOREIGN KEY (`idCity`) REFERENCES city (`idCity`);

ALTER TABLE computers ADD FOREIGN KEY (`idPerson`) REFERENCES person (`idPerson`);

ALTER TABLE computers ADD FOREIGN KEY (`idOffice`) REFERENCES office (`idOffice`);

ALTER TABLE computers ADD FOREIGN KEY (`idInvoice`) REFERENCES invoice (`idInvoice`);

ALTER TABLE computers ADD FOREIGN KEY (`idStatusComputer`) REFERENCES statusComputer (`idStatusComputer`);

ALTER TABLE comments ADD FOREIGN KEY (`idPerson`) REFERENCES person (`idPerson`);

ALTER TABLE comments ADD FOREIGN KEY (`idDevice`) REFERENCES device (`idDevice`);

ALTER TABLE comments ADD FOREIGN KEY (`idComputers`) REFERENCES computers (`idComputers`);

ALTER TABLE device ADD FOREIGN KEY (`idPerson`) REFERENCES person (`idPerson`);

ALTER TABLE device ADD FOREIGN KEY (`idInvoice`) REFERENCES invoice (`idInvoice`);

ALTER TABLE device ADD FOREIGN KEY (`idStatus`) REFERENCES statusComputer (`idStatusComputer`);

ALTER TABLE users ADD FOREIGN KEY (`idUser`) REFERENCES person (`idPerson`);
